[package]
name = "CrossChainToken"
version = "0.1.0"
authors = []

[addresses]
cross_chain_token = "0x1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }

[dev-dependencies]